// <auto-generated />
namespace commerce_bot_mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class foodupdate2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foodupdate2));
        
        string IMigrationMetadata.Id
        {
            get { return "201802230734596_food-update2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
