// <auto-generated />
namespace commerce_bot_mvc.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mainlogic : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mainlogic));
        
        string IMigrationMetadata.Id
        {
            get { return "201802192204203_main-logic"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
