//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int Id { get; set; }
        public int FoodCategoryId { get; set; }
        public int RestaurantId { get; set; }
        public string DishName { get; set; }
        public Nullable<double> Price { get; set; }
        public string Portion { get; set; }
        public string DishDescription { get; set; }
    
        public virtual FoodCategory FoodCategory { get; set; }
    }
}
